---
title: "Lab Week 8"
author: "Austin Richards"
date: "3/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###Load the packages

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)
library(ggthemes)
```

###Colum graph of Texas oil spills

```{r}
oil_spills <- read_csv("oil_spills.csv")

df <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` < 2017) %>% 
  group_by(`Accident Year`) %>% 
  summarise(Loss = sum(`Net Loss (Barrels)`))

colnames(df) <- c("Year", "Loss")

ggplot(df, aes(x = Year, y= Loss))+
  geom_col()+
  theme_economist()

```



```{r}
df_loc <-oil_spills %>% 
  filter(`Accident State`== "TX" & `Accident Year` == "2016") %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)

colnames(df_loc) <- c("latitude", "longitude", "net_loss")

oil_sf <- st_as_sf(df_loc, coords = c("longitude", "latitude"), crs = 4326) #convert current df into simple feature spatial data

leaflet(oil_sf) %>% 
  addTiles() %>% #base graph
  addMarkers()
```


##tmap plot with the Texas state shapefile
```{r}

states <- st_read(dsn = ".", layer = "states") 

tex_border <- states %>% 
  filter(STATE_NAME == "Texas") %>% 
  st_transform(4326) #this converts to the coordinate refrence system that we want

plot(tex_border)

tm_shape(tex_border) +
  tm_polygons () +
  tm_shape(oil_sf) +
  tm_dots(size = 0.3)

```


###Convert the data to spatial poin patterns (combination of point data and the bounding window)


```{r}
spill_sp <- as(oil_sf, "Spatial")
spill_ppp <- as(spill_sp, "ppp")

tx_sp <- as(tex_border, "Spatial")

tx_owin <- as(tx_sp, "owin") #make this border the outer window for ppp

all_ppp <-ppp(spill_ppp$x, spill_ppp$y, window = tx_owin)

```






